services:
  - type: web
    name: alwissam
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npx prisma db seed && next start
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
