services:
  - type: web
    name: alwissam
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    preDeployCommand: npx prisma migrate deploy
    startCommand: npx prisma migrate deploy && next start -H 0.0.0.0 -p $PORT
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 22
